import type { University } from '../universities';

const checkedAt = '28 июля 2026';

export const asiaUniversities: University[] = [
  {
    id: 'nus',
    name: 'National University of Singapore',
    shortName: 'NUS',
    location: 'Singapore, Сингапур',
    summary: 'Крупный исследовательский университет с сильными программами в технологиях, науке и бизнесе.',
    testPolicy: 'course-dependent',
    testNote: 'Нужные экзамены зависят от школьной квалификации и выбранной программы.',
    englishNote: 'Подтверждение английского зависит от школьной квалификации.',
    deadlines: 'На 2026/27 учебный год: международные заявки принимались с 3 декабря 2025 до 23 февраля 2026.',
    documents: ['Онлайн-заявка NUS', 'Школьные оценки', 'Результаты экзаменов', 'Документы по программе'],
    opportunities: ['Исследования', 'Стартапы', 'Международные обмены'],
    sourceUrl: 'https://www.nus.edu.sg/oam/admissions/international-qualifications-for-foreigners',
    checkedAt,
  },
  {
    id: 'ntu-singapore',
    name: 'Nanyang Technological University',
    shortName: 'NTU Singapore',
    location: 'Singapore, Сингапур',
    summary: 'Технологический университет с сильными инженерными, научными и бизнес-программами.',
    testPolicy: 'course-dependent',
    testNote: 'SAT, ACT или другой экзамен может требоваться в зависимости от аттестата.',
    englishNote: 'Для некоторых квалификаций нужен IELTS от 6.0 или другой принятый экзамен.',
    englishMinimum: 6,
    deadlines: 'Срок подачи зависит от школьной квалификации; проверяй таблицу текущего цикла.',
    documents: ['Онлайн-заявка NTU', 'Аттестат и оценки', 'Результаты экзаменов', 'Подтверждение английского'],
    opportunities: ['Инженерные проекты', 'Исследования', 'Предпринимательство'],
    sourceUrl: 'https://www.ntu.edu.sg/admissions/undergraduate/admission-guide/international-qualifications',
    checkedAt,
  },
  {
    id: 'tsinghua',
    name: 'Tsinghua University',
    shortName: 'Tsinghua',
    location: 'Beijing, Китай',
    summary: 'Ведущий исследовательский университет Китая, особенно сильный в инженерии и технологиях.',
    testPolicy: 'course-dependent',
    testNote: 'Формат оценки и экзамены зависят от программы и языка обучения.',
    englishNote: 'Для англоязычных программ нужно подтвердить английский; для китайских — знание китайского.',
    deadlines: 'Даты и этапы отличаются по программам — проверь текущую международную приёмную кампанию.',
    documents: ['Онлайн-заявка', 'Аттестат и транскрипт', 'Personal statement', 'Языковой сертификат'],
    opportunities: ['STEM-исследования', 'Лаборатории', 'Международные программы'],
    sourceUrl: 'https://international.join-tsinghua.edu.cn/',
    checkedAt,
  },
  {
    id: 'tokyo',
    name: 'The University of Tokyo',
    shortName: 'UTokyo',
    location: 'Tokyo, Япония',
    summary: 'Главный исследовательский университет Японии с сильными программами во многих областях.',
    testPolicy: 'course-dependent',
    testNote: 'Правила зависят от пути поступления; большинство бакалаврских программ ведётся на японском.',
    englishNote: 'Языковое требование зависит от программы: может понадобиться японский или английский.',
    deadlines: 'PEAK завершил последний набор на сентябрь 2026; для 2027 года проверь другие международные пути.',
    documents: ['Заявка', 'Школьные оценки', 'Результаты экзаменов', 'Подтверждение языка'],
    opportunities: ['Исследования', 'Лаборатории', 'Японский язык и культура'],
    sourceUrl: 'https://www.u-tokyo.ac.jp/en/prospective-students/undergraduate_english.html',
    checkedAt,
  },
  {
    id: 'seoul-national',
    name: 'Seoul National University',
    shortName: 'SNU',
    location: 'Seoul, Южная Корея',
    summary: 'Ведущий корейский университет с широким выбором направлений и сильной исследовательской базой.',
    testPolicy: 'course-dependent',
    testNote: 'Отбор основан на документах; отдельные программы могут проводить интервью или проверку навыков.',
    englishNote: 'Можно приложить подтверждение корейского или английского согласно требованиям программы.',
    deadlines: 'На весну 2027 года: онлайн-заявка с 6 до 9 июля 2026, рекомендация — до 10 июля.',
    documents: ['Онлайн-заявка', 'Транскрипт', 'Personal statement и учебный план', 'Рекомендация'],
    opportunities: ['Исследования', 'Корейский язык', 'Международные программы'],
    sourceUrl: 'https://en.snu.ac.kr/admission/undergraduate/application',
    checkedAt,
  },
  {
    id: 'hku',
    name: 'The University of Hong Kong',
    shortName: 'HKU',
    location: 'Hong Kong, Китай',
    summary: 'Международный исследовательский университет с программами на английском языке.',
    testPolicy: 'course-dependent',
    testNote: 'Принимаются разные международные и национальные экзамены; возможны интервью.',
    englishNote: 'Нужно выполнить требование по английскому для выбранной квалификации и программы.',
    deadlines: 'Международная заявка открывается осенью; поздние заявки рассматриваются при наличии мест.',
    documents: ['Онлайн-заявка', 'Аттестат и оценки', 'Personal statement', 'Подтверждение английского'],
    opportunities: ['Исследования', 'Обучение на английском', 'Международные обмены'],
    sourceUrl: 'https://admissions.hku.hk/apply/international-qualifications',
    checkedAt,
  },
  {
    id: 'hkust',
    name: 'Hong Kong University of Science and Technology',
    shortName: 'HKUST',
    location: 'Hong Kong, Китай',
    summary: 'Технологический университет с сильными программами в инженерии, науке и бизнесе.',
    testPolicy: 'course-dependent',
    testNote: 'Требования зависят от школьной квалификации и выбранной школы или программы.',
    englishNote: 'Нужно подтвердить английский согласно таблице международных квалификаций.',
    deadlines: 'На 2026/27 год: Early Round до 20 ноября, Main Round до 8 января.',
    documents: ['Онлайн-заявка', 'Оценки за три года', 'Personal statement', 'Рекомендация'],
    opportunities: ['Инженерия', 'Бизнес', 'Стартапы и исследования'],
    sourceUrl: 'https://join.hkust.edu.hk/admissions/international-qualifications',
    checkedAt,
  },
  {
    id: 'kaist',
    name: 'Korea Advanced Institute of Science and Technology',
    shortName: 'KAIST',
    location: 'Daejeon, Южная Корея',
    summary: 'Научно-технический университет с гибким выбором специальности после первого курса.',
    testPolicy: 'course-dependent',
    testNote: 'Экзаменационные результаты учитываются по правилам международного набора; интервью назначают не всем.',
    englishNote: 'В заявке можно представить принятое подтверждение владения английским.',
    deadlines: 'Сроки Early и Regular меняются каждый цикл; проверь календарь международного набора.',
    documents: ['Онлайн-заявка', 'Транскрипт', 'Рекомендация', 'Результаты экзаменов'],
    opportunities: ['STEM', 'Исследования', 'Выбор специальности после первого курса'],
    sourceUrl: 'https://admission.kaist.ac.kr/intl-undergraduate/application',
    checkedAt,
  },
];
