import type { University } from '../universities';

const checkedAt = '28 июля 2026';

export const ukUniversities: University[] = [
  {
    id: 'oxford',
    name: 'University of Oxford',
    shortName: 'Oxford',
    location: 'Oxford, Великобритания',
    summary: 'Коллегиальный университет с персональными tutorials и сильными академическими программами.',
    testPolicy: 'course-dependent',
    testNote: 'Некоторые программы требуют ESAT, TMUA, TARA, LNAT или UCAT.',
    englishNote: 'Для всех программ требуется высокий уровень английского; ориентир IELTS Academic — 7.5.',
    englishMinimum: 7.5,
    deadlines: 'Для поступления в 2027 году: UCAS до 15 октября 2026, 18:00 по времени Великобритании.',
    documents: ['UCAS', 'Школьные оценки и прогноз', 'Академическая рекомендация', 'Иногда письменная работа'],
    opportunities: ['Tutorials', 'Колледжи', 'Исследовательские библиотеки'],
    sourceUrl: 'https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants',
    checkedAt,
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    shortName: 'Cambridge',
    location: 'Cambridge, Великобритания',
    summary: 'Коллегиальный университет с обучением в малых группах и сильной исследовательской средой.',
    testPolicy: 'course-dependent',
    testNote: 'Для ряда программ нужны ESAT, TMUA, UCAT или оценивание колледжа.',
    englishNote: 'Нужен высокий уровень английского; точное подтверждение зависит от условий предложения.',
    deadlines: 'Для поступления в 2027 году: UCAS до 15 октября 2026, 18:00 по времени Великобритании.',
    documents: ['UCAS', 'My Cambridge Application', 'Транскрипт при необходимости', 'Академическая рекомендация'],
    opportunities: ['Supervisions', 'Колледжи', 'Исследования'],
    sourceUrl: 'https://www.undergraduate.study.cam.ac.uk/apply/application-dates-deadlines',
    checkedAt,
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    shortName: 'Imperial',
    location: 'London, Великобритания',
    summary: 'Лондонский университет, специализирующийся на науке, инженерии, медицине и бизнесе.',
    testPolicy: 'course-dependent',
    testNote: 'Тест зависит от программы: встречаются ESAT, TMUA и UCAT.',
    englishNote: 'Требование зависит от программы: обычно Standard или Higher level.',
    englishMinimum: 6.5,
    deadlines: 'Подача через UCAS; для большинства программ действует январский дедлайн, для Medicine — октябрьский.',
    documents: ['UCAS', 'Школьные оценки и прогноз', 'Академическая рекомендация', 'Подтверждение английского'],
    opportunities: ['STEM-лаборатории', 'Лондонская индустрия', 'Предпринимательство'],
    sourceUrl: 'https://www.imperial.ac.uk/study/apply/undergraduate/',
    checkedAt,
  },
  {
    id: 'st-andrews',
    name: 'University of St Andrews',
    shortName: 'St Andrews',
    location: 'St Andrews, Шотландия',
    summary: 'Старинный шотландский университет с гибкой системой обучения и небольшим студенческим сообществом.',
    testPolicy: 'course-dependent',
    testNote: 'Дополнительные испытания зависят от программы; для Medicine действуют отдельные требования.',
    englishNote: 'Требование по английскому зависит от факультета и программы.',
    deadlines: 'Для поступления в 2027 году: Medicine — до 15 октября 2026, остальные программы — до 13 января 2027.',
    documents: ['UCAS', 'Оценки и прогноз', 'Академическая рекомендация', 'Подтверждение английского'],
    opportunities: ['Гибкий выбор предметов', 'Исследования', 'Международное сообщество'],
    sourceUrl: 'https://www.st-andrews.ac.uk/study/undergraduate/apply/ucas/',
    checkedAt,
  },
  {
    id: 'edinburgh',
    name: 'The University of Edinburgh',
    shortName: 'Edinburgh',
    location: 'Edinburgh, Великобритания',
    summary: 'Исторический шотландский университет с сильными исследованиями и международным сообществом.',
    testPolicy: 'course-dependent',
    testNote: 'Большинство программ оценивает школьные квалификации; отдельные направления требуют тест.',
    englishNote: 'Минимум по английскому зависит от программы — проверь требования выбранного курса.',
    deadlines: 'Подача через UCAS; дедлайн зависит от программы и цикла поступления.',
    documents: ['UCAS', 'Оценки и прогноз', 'Академическая рекомендация', 'Подтверждение английского'],
    opportunities: ['Исследования', 'Студенческие общества', 'Международная среда'],
    sourceUrl: 'https://study.ed.ac.uk/undergraduate/applying/international',
    checkedAt,
  },
  {
    id: 'lse',
    name: 'London School of Economics and Political Science',
    shortName: 'LSE',
    location: 'London, Великобритания',
    summary: 'Специализированный университет в области экономики, политики и общественных наук.',
    testPolicy: 'course-dependent',
    testNote: 'Для некоторых программ или квалификаций нужны TMUA, LNAT или UGAA.',
    englishNote: 'Уровень английского зависит от программы и условий предложения.',
    deadlines: 'Для поступления в 2027 году: UCAS до 13 января 2027, 18:00 по времени Великобритании.',
    documents: ['UCAS', 'Оценки и прогноз', 'Personal statement', 'Академическая рекомендация'],
    opportunities: ['Экономика', 'Политика', 'Лондонская профессиональная среда'],
    sourceUrl: 'https://www.lse.ac.uk/study-at-lse/Undergraduate/Prospective-Students/How-to-apply',
    checkedAt,
  },
  {
    id: 'kings',
    name: "King's College London",
    shortName: "King's",
    location: 'London, Великобритания',
    summary: 'Лондонский исследовательский университет с сильными программами в медицине и гуманитарных науках.',
    testPolicy: 'course-dependent',
    testNote: 'Тесты и интервью зависят от программы; для Medicine действует отдельный порядок.',
    englishNote: 'Требование по английскому указано на странице выбранной программы.',
    deadlines: 'Подача через UCAS; Medicine и Dentistry имеют ранний октябрьский дедлайн.',
    documents: ['UCAS', 'Оценки и прогноз', 'Академическая рекомендация', 'Подтверждение английского'],
    opportunities: ['Медицина', 'Гуманитарные науки', 'Учёба в центре Лондона'],
    sourceUrl: 'https://www.kcl.ac.uk/study/undergraduate/how-to-apply',
    checkedAt,
  },
  {
    id: 'manchester',
    name: 'The University of Manchester',
    shortName: 'Manchester',
    location: 'Manchester, Великобритания',
    summary: 'Крупный исследовательский университет с широким выбором научных и гуманитарных программ.',
    testPolicy: 'course-dependent',
    testNote: 'Дополнительные требования зависят от курса; Medicine и Dentistry рассматриваются отдельно.',
    englishNote: 'Обычно IELTS 6.0–7.0 в зависимости от программы.',
    englishMinimum: 6,
    deadlines: 'Подача через UCAS; лучше подать к январскому equal consideration deadline.',
    documents: ['UCAS', 'Оценки и прогноз', 'Академическая рекомендация', 'Подтверждение английского'],
    opportunities: ['Исследования', 'Большой выбор программ', 'Студенческое сообщество'],
    sourceUrl: 'https://www.manchester.ac.uk/study/international/admissions/undergraduate-application-process/',
    checkedAt,
  },
];
