import type { University } from '../universities';

export const usUniversities: University[] = [
  {
    id: 'stanford',
    name: 'Stanford University',
    shortName: 'Stanford',
    location: 'Stanford, California',
    summary: 'Сильная исследовательская среда рядом с Кремниевой долиной.',
    testPolicy: 'required',
    englishNote: 'IELTS/TOEFL не обязательны, но английский должен быть свободным.',
    deadlines: 'Обычно: 1 ноября — ранняя подача, 5 января — обычная.',
    documents: ['Common Application', 'Транскрипт', 'Рекомендация counselor', '2 рекомендации учителей'],
    opportunities: ['Исследования', 'Стартап-среда', 'Междисциплинарные программы'],
    sourceUrl: 'https://admission.stanford.edu/apply/first-year/index.html',
    checkedAt: '28 июля 2026',
  },
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    shortName: 'MIT',
    location: 'Cambridge, Massachusetts',
    summary: 'Технологический университет с упором на науку, инженерию и практику.',
    testPolicy: 'required',
    englishNote: 'Для некоторых иностранных абитуриентов экзамен рекомендован: IELTS от 7.0, желательно 7.5.',
    englishMinimum: 7,
    deadlines: 'Обычно: 1 ноября — Early Action, 5 января — Regular Action.',
    documents: ['Заявка MIT', 'Школьные оценки', 'Эссе', 'Рекомендации', 'SAT или ACT'],
    opportunities: ['Лаборатории', 'Инженерные проекты', 'Предпринимательство'],
    sourceUrl: 'https://mitadmissions.org/apply/firstyear/international/',
    checkedAt: '28 июля 2026',
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    shortName: 'Harvard',
    location: 'Cambridge, Massachusetts',
    summary: 'Университет с широким выбором направлений и сильной системой финансовой помощи.',
    testPolicy: 'required',
    englishNote: 'IELTS/TOEFL для first-year не обязательны, но их можно отправить.',
    deadlines: 'Обычно: 1 ноября — ранняя подача, 1 января — обычная.',
    documents: ['Common Application', 'Harvard supplement', 'Транскрипт', 'Рекомендации', 'SAT или ACT'],
    opportunities: ['Need-based помощь', 'Исследования', 'Большой выбор дисциплин'],
    sourceUrl: 'https://college.harvard.edu/admissions/apply/international-applicants',
    checkedAt: '28 июля 2026',
  },
  {
    id: 'berkeley',
    name: 'University of California, Berkeley',
    shortName: 'UC Berkeley',
    location: 'Berkeley, California',
    summary: 'Крупный государственный исследовательский университет.',
    testPolicy: 'not-considered',
    englishNote: 'При неанглоязычном обучении IELTS обычно требуется от 6.5.',
    englishMinimum: 6.5,
    deadlines: 'Подача через систему University of California; даты нужно проверять каждый цикл.',
    documents: ['UC Application', 'Оценки и предметы', 'Personal Insight Questions', 'Подтверждение английского'],
    opportunities: ['Исследования', 'Сильные STEM-программы', 'Большое международное сообщество'],
    sourceUrl: 'https://admissions.berkeley.edu/requirements-for-international-students/',
    checkedAt: '28 июля 2026',
  },
  {
    id: 'princeton',
    name: 'Princeton University',
    shortName: 'Princeton',
    location: 'Princeton, New Jersey',
    summary: 'Исследовательский университет с сильным бакалавриатом и обучением в небольших группах.',
    testPolicy: 'course-dependent',
    testNote: 'Политика стандартизированных тестов зависит от цикла поступления.',
    englishNote: 'Для части иностранных абитуриентов требуется TOEFL, IELTS или другой принятый тест.',
    deadlines: 'Обычно: 1 ноября — Single-Choice Early Action, начало января — Regular Decision.',
    documents: ['Common Application', 'Princeton Questions', 'Транскрипт', 'Рекомендации'],
    opportunities: ['Исследования', 'Небольшие классы', 'Need-based помощь'],
    sourceUrl: 'https://admission.princeton.edu/apply/first-year-application-dates-deadlines',
    checkedAt: '28 июля 2026',
  },
  {
    id: 'yale',
    name: 'Yale University',
    shortName: 'Yale',
    location: 'New Haven, Connecticut',
    summary: 'Университет с сильными гуманитарными, общественными и естественно-научными программами.',
    testPolicy: 'required',
    englishNote: 'Для части иностранных абитуриентов требуется подтверждение английского.',
    deadlines: 'Обычно: 1 ноября — Single-Choice Early Action, начало января — Regular Decision.',
    documents: ['Common Application', 'Yale supplement', 'Транскрипт', 'Рекомендации', 'Результаты тестов'],
    opportunities: ['Residential colleges', 'Исследования', 'Искусство и культура'],
    sourceUrl: 'https://admissions.yale.edu/international',
    checkedAt: '28 июля 2026',
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology',
    shortName: 'Caltech',
    location: 'Pasadena, California',
    summary: 'Небольшой научно-технический университет с интенсивной исследовательской подготовкой.',
    testPolicy: 'required',
    englishNote: 'Иностранным абитуриентам обычно нужен IELTS, TOEFL или Duolingo, если школа не англоязычная.',
    deadlines: 'Обычно: 1 ноября — Restrictive Early Action, начало января — Regular Decision.',
    documents: ['Common Application', 'Caltech Questions', 'Транскрипт', 'Рекомендации', 'SAT или ACT'],
    opportunities: ['Лаборатории', 'STEM-исследования', 'Небольшое сообщество'],
    sourceUrl: 'https://www.admissions.caltech.edu/apply/first-year-applicants/international-applicants',
    checkedAt: '28 июля 2026',
  },
];
